### ISSUE TITLE
negated character class?

### ISSUE THREAD

**Issue by metaperl** [manoss96/pregex#13]
I was considering using this to develop a negated character class for the following:

> take a string and replace any non-alpha-numeric character with underscore

I ended up just using `re` and going with:

> take a string and replace any non-word-numeric character with underscore

```python
def clean_title(t: str) -> str:
    _ = re.sub(r'\W', '_', t)
    logger.debug(f"{t=}, {_=}")
```

**Comment by manoss96** [comment]
Hey there! I don't quite get what's the issue. Could you explain?

**Comment by metaperl** [comment]
How do you implement negated character classes in pregex? I did not see anything in the docs regarding that.

**Comment by manoss96** [comment]
You can read all about character classes [here](https://pregex.readthedocs.io/en/latest/documentation/modules/core/classes.html). In general, you can either directly use a negated character class:
```python
from pregex import *

pre = cl.AnyButWordCharacter()
```
or negate a regular character class via operator "~":
```python
from pregex import *

pre = ~ cl.AnyWordCharacter()
```
