### ISSUE TITLE
Case Insensitive Modifiers

### ISSUE THREAD

**Issue by lhegstrom** [manoss96/pregex#14]
This project is awesome! One feature I noticed may be missing is the ability to add a case insensitive modifier.

Something along the lines of:

`CaseInsensitive('without' + AtMost(Any(), n=30) + 'evidence')`

that would wrap the regex in `(?i)   ...   (?-i)`?

**Comment by manoss96** [comment]
Hey there, glad you like the project! Yeah, you're right there's no such feature as of yet but I'll make a note of it to include it in the next version, since it can indeed be very useful.

**Comment by manoss96** [comment]
Closing this issue as, as of pregex v2.3.0, the case insensitive modifier can be applied to an entire non-capturing group. See [PRegEx v2.3.0 Release Notes](https://github.com/manoss96/pregex/releases/tag/v2.3.0).
