### ISSUE TITLE
How to get text in outer brackets?

### ISSUE THREAD

**Issue by elkarouh** [manoss96/pregex#17]
Hello,
Just discovered this package, very cool !!!
I have a question though.
I have the following text:
text="000[111[222[333]222]111]000"
and i would like to retrieve the text with the outer brackets '111[222[333]222]111'
This is simple in pure python but i want to do it with a regular expression.
Any idea?
Regards

**Comment by manoss96** [comment]
Hey there! Generally, RegEx is not the best choice when it comes to nested patterns such as this. However, based on the specific example you have provided, there is a RegEx pattern that is able to achieve what you want:
```python
    text = qu.OneOrMore(cl.Any())
    text_containing_right_bracket = op.Enclose("]", text)

    pre = (
        cl.AnyDigit().preceded_by('[') +
        text +
        asr.NotFollowedBy(cl.AnyDigit().followed_by(']'), text_containing_right_bracket)
    )

    result = pre.get_matches("000[111[222[333]222]111]000")
```
The RegEx pattern represented by "pre" is the following: ``(?<=\[)\d.+\d(?=\])(?!.+\].+)``

**Comment by elkarouh** [comment]
Perfect !
Many thanks.
