### ISSUE TITLE
Use the Pypi 'regex' module instead of the built-in 're' module

### ISSUE THREAD

**Issue by elkarouh** [manoss96/pregex#19]
I came across a limitation of the re module. 
The regex module [https://pypi.org/project/regex/](url) doesn't have it.
I am trying to write an assertion to reject matches within brackets (parentheses)

``` 
def Not_within_brackets(pre): 
    anytext_re = Indefinite(Any())
    return pre.not_preceded_by(Pregex("(").enclose(anytext_re)).not_followed_by(Pregex(")").enclose(anytext_re))
pre=Not_within_brackets(Pregex("one"))
text="(not this one) this one"
print(pre.get_matches(text))
```
I get the following error from the underlying re module:
```re.error: look-behind requires fixed-width pattern```

I would like to use the regex module instead, unless there is another solution to this problem.

Many thanks !!!

**Comment by manoss96** [comment]
PRegEx uses Python's built-in re module underneath which indeed does not support variable-width lookbehind assertions. I'm not sure exactly what you are trying to do, but I'm guessing it's something to the likes of _match pattern X only if X is not enclosed by parentheses_. E.g. given the text ``X X (X)``, you only want to match the first two Xs. In that case, having ``Pregex("X").not_preceded_by("(").not_followed_by(")")`` will suffice. However, if you'd like to work with texts like ``X X (X  X  X) X (X  X  X)``, where you are to reject any match within the parentheses, then this would be a bit difficult to achieve with RegEx/PRegEx.

**Comment by elkarouh** [comment]
Thank you for the clarification!
