### ISSUE TITLE
Cannot install pregex

### ISSUE THREAD

**Issue by hiennguyen15** [manoss96/pregex#2]
Is there any way to install this package rather than pip install pregex? I face this error.
<img width="523" alt="image" src="https://user-images.githubusercontent.com/46238740/182020645-dbd3ae83-dea3-4427-9f9b-5dc4a5d9bbc5.png">

**Comment by manoss96** [comment]
> Is there any way to install this package rather than pip install pregex? I face this error. <img alt="image" width="523" src="https://user-images.githubusercontent.com/46238740/182020645-dbd3ae83-dea3-4427-9f9b-5dc4a5d9bbc5.png">
Greetings! I suspect that this error is due to an incorrect Python version. Make sure that you are trying to install pregex in Python 3.9.

**Comment by hiennguyen15** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/46238740/182021561-5fe71982-1c85-419f-b785-e3ad9e3474e9.png">
Actually my python is 3.9 already

**Comment by manoss96** [comment]
> 

Try maybe installing with "python -m pip install pregex" and tell me what happens.

**Comment by hiennguyen15** [comment]
I think, I got problem with default Python version in my mac. May need to remove older version first. Thanks anw

**Comment by manoss96** [comment]
> I think, I got problem with default Python version in my mac. May need to remove older version first. Thanks anw

Okay, I'm closing the issue
