### ISSUE TITLE
Examples for Backreference, Conditional 

### ISSUE THREAD

**Issue by hcchengithub** [manoss96/pregex#20]
Where to find examples especially Backreference and Conditional?
Thank you very much.

**Comment by manoss96** [comment]
All Pregex instances represent pure RegEx strings underneath, which you can fetch by invoking an instances ``get_pattern`` method. Therefore, by reading on RegEx [backreferences](https://www.regular-expressions.info/backref.html) and [conditionals,](https://www.regular-expressions.info/conditional.html) you immediately know how their PRegEx equivalents work.

Furthermore, you can read more about these classes and their parameters in PRegEx's documentation page, more specifically in its [pregex.core.groups section](https://pregex.readthedocs.io/en/latest/documentation/modules/core/groups.html)

**Comment by hcchengithub** [comment]
The document is good and I answered the question: 
```
pattern = Capture(Any()) + Backreference(1)
pattern.get_matches("this is a book")
# ['oo']

pattern = Capture(Any(),name="any") + Backreference(1) + Conditional('any','s')
pattern.get_matches("The quick brown fox jumps over the lazzy dog by the lady goose in the farm of freedom.")
# ['oos'] 

```
