### ISSUE TITLE
pre.split_by_match differs re.split with pros and cons

### ISSUE THREAD

**Issue by hcchengithub** [manoss96/pregex#27]
Simply use re when wanting its pros, right? or pre has a better way?

I prefer pre's behavior:
```
Pregex('aa').split_by_match("12aa34") --> ['12', '34']
Pregex('aa').split_by_match("12aa34aa") --> ['12', '34']
Pregex('aa').split_by_match("12aa34aaaa") --> ['12', '34']
```

But re has its pros:
```
re.split('aa',"12aa34") --> ['12', '34']
re.split('aa',"12aa34aa") --> ['12', '34', '']
re.split('aa',"12aa34aaaa") --> ['12', '34', '', '']
```
Guarantee there was a delimiter in between each matches.

**Comment by hcchengithub** [comment]
Now I have realized PRegEx helps to generate the re pattern and that's perfect enough. One more difference is that `re.split(pattern, string, maxsplit=0, flags=0)` has parameter maxsplit while pre.split_by_match() has not. Such differences can be growing in the future while re is.

**Comment by manoss96** [comment]
As of yet, ``Pregex.split_by_match`` has its own implementation which means that it doesn't use ``re.split`` internally. Maybe its for the best that I make it so that ``re.split`` is used, thus incorporating more of its parameters like ``maxsplit``.

**Comment by hcchengithub** [comment]
Helps to generate re patterns is the unique function of PRegEx; .split_by_'s are nice to have while re.sub can do them too. Thus this issue can be closed.
