### ISSUE TITLE
 I hope you can make a class for Korean.

### ISSUE THREAD

**Issue by sungreong** [manoss96/pregex#7]
I am making the following code for Korean.
If Korean is reflected officially, I think many Koreans will use it. :)

```
from pregex.core.classes import AnyLetter
class AnyKor(AnyLetter):

    def __init__(self) -> 'AnyKor':
        '''
        Matches any character from the Latin alphabet.
        '''
        super(AnyLetter,self).__init__('[ㄱ-ㅎ|가-힣]', is_negated=False)
```

**Comment by manoss96** [comment]
Hey there, Sure the more the better! I am keeping this issue open so I'll remember to include this in the next version!

**Comment by manoss96** [comment]
@sungreong Hi again! I am looking at this [Korean character set](https://memory.loc.gov/diglib/codetables/9.3.html) and I am noticing that some of these characters are missing from your RegEx. I don't know Korean, so I'm just asking you to make sure if it's okay to skip these characters.

**Comment by manoss96** [comment]
Closing this issue as Korean class has been added. If something's wrong with it you can open a new issue.
